'use client'

import { useState, useEffect } from 'react'
import { supabase } from '@/lib/supabase'
import { useSectionStatus, useUserContext } from '@/lib/hooks/useVaultAccess'
import { CONTRACT_TYPE_LABELS, ContractType } from '@/lib/types'

export default function ExportPage() {
  const { context } = useUserContext()
  const { completeness } = useSectionStatus()

  const [isLoading, setIsLoading] = useState(false)
  const [exportData, setExportData] = useState<any>(null)
  const [selectedSections, setSelectedSections] = useState({
    contracts: true,
    digital: true,
    physical: true,
    subscriptions: true,
    contacts: true,
  })
  const [exportFormat, setExportFormat] = useState<'pdf' | 'csv' | 'json'>('pdf')

  useEffect(() => {
    async function fetchData() {
      const { data: { session } } = await supabase.auth.getSession()
      if (!session?.user) return

      const [contracts, digital, physical, subscriptions, contacts] = await Promise.all([
        supabase.from('contracts').select('*').eq('user_id', session.user.id),
        supabase.from('digital_assets').select('*').eq('user_id', session.user.id),
        supabase.from('physical_assets').select('*').eq('user_id', session.user.id),
        supabase.from('subscriptions').select('*').eq('user_id', session.user.id),
        supabase.from('contacts').select('*').eq('user_id', session.user.id),
      ])

      setExportData({
        contracts: contracts.data || [],
        digital: digital.data || [],
        physical: physical.data || [],
        subscriptions: subscriptions.data || [],
        contacts: contacts.data || [],
      })
    }
    fetchData()
  }, [])

  const downloadFile = (content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const generatePDF = () => {
    if (!exportData) return
    setIsLoading(true)
    const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    
    let sectionsHtml = ''
    
    if (selectedSections.contracts && exportData.contracts.length > 0) {
      sectionsHtml += `<h2>Contracts & Legal (${exportData.contracts.length})</h2>`
      exportData.contracts.forEach((c: any) => {
        sectionsHtml += `<div class="item"><div class="item-name">${c.name}</div><div class="item-detail">Type: ${CONTRACT_TYPE_LABELS[c.type as ContractType] || c.type}</div></div>`
      })
    }
    
    if (selectedSections.digital && exportData.digital.length > 0) {
      sectionsHtml += `<h2>Digital Infrastructure (${exportData.digital.length})</h2>`
      exportData.digital.forEach((d: any) => {
        sectionsHtml += `<div class="item"><div class="item-name">${d.name}</div><div class="item-detail">Type: ${d.type}</div></div>`
      })
    }

    if (selectedSections.physical && exportData.physical.length > 0) {
      sectionsHtml += `<h2>Physical Assets (${exportData.physical.length})</h2>`
      exportData.physical.forEach((p: any) => {
        sectionsHtml += `<div class="item"><div class="item-name">${p.name}</div><div class="item-detail">Type: ${p.type}</div></div>`
      })
    }

    if (selectedSections.subscriptions && exportData.subscriptions.length > 0) {
      sectionsHtml += `<h2>Subscriptions (${exportData.subscriptions.length})</h2>`
      exportData.subscriptions.forEach((s: any) => {
        sectionsHtml += `<div class="item"><div class="item-name">${s.name}</div><div class="item-detail">Provider: ${s.provider}</div></div>`
      })
    }

    if (selectedSections.contacts && exportData.contacts.length > 0) {
      sectionsHtml += `<h2>Key Relationships (${exportData.contacts.length})</h2>`
      exportData.contacts.forEach((c: any) => {
        sectionsHtml += `<div class="item"><div class="item-name">${c.name}</div><div class="item-detail">Role: ${c.role}</div></div>`
      })
    }

    const html = `<!DOCTYPE html><html><head><title>Deal Readiness Report</title><style>body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;padding:40px;color:#1a1a1a}h1{font-size:24px;margin-bottom:8px}h2{font-size:18px;margin-top:32px;margin-bottom:16px;border-bottom:2px solid #f59e0b;padding-bottom:8px}.subtitle{color:#666;margin-bottom:24px}.item{margin-bottom:16px;padding:12px;background:#f9f9f9;border-radius:8px}.item-name{font-weight:600}.item-detail{font-size:14px;color:#666;margin-top:4px}.footer{margin-top:40px;padding-top:20px;border-top:1px solid #eee;font-size:12px;color:#999}</style></head><body><h1>Deal Readiness Report</h1><p class="subtitle">Generated on ${date}</p>${sectionsHtml}<div class="footer"><p>Generated by Deal-Ready Vault</p></div></body></html>`

    const printWindow = window.open('', '_blank')
    if (printWindow) {
      printWindow.document.write(html)
      printWindow.document.close()
      printWindow.print()
    }
    setIsLoading(false)
  }

  const generateCSV = () => {
    if (!exportData) return
    setIsLoading(true)
    let csv = 'Section,Name,Type,Details\n'
    if (selectedSections.contracts) exportData.contracts.forEach((c: any) => { csv += `"Contracts","${c.name}","${c.type}","${c.counterparty || ''}"\n` })
    if (selectedSections.digital) exportData.digital.forEach((d: any) => { csv += `"Digital","${d.name}","${d.type}","${d.provider || ''}"\n` })
    if (selectedSections.physical) exportData.physical.forEach((p: any) => { csv += `"Physical","${p.name}","${p.type}","${p.location || ''}"\n` })
    if (selectedSections.subscriptions) exportData.subscriptions.forEach((s: any) => { csv += `"Subscriptions","${s.name}","${s.provider}",""\n` })
    if (selectedSections.contacts) exportData.contacts.forEach((c: any) => { csv += `"Contacts","${c.name}","${c.role}","${c.organization || ''}"\n` })
    downloadFile(csv, 'deal-readiness-report.csv', 'text/csv')
    setIsLoading(false)
  }

  const generateJSON = () => {
    if (!exportData) return
    setIsLoading(true)
    const data: any = {}
    if (selectedSections.contracts) data.contracts = exportData.contracts
    if (selectedSections.digital) data.digital = exportData.digital
    if (selectedSections.physical) data.physical = exportData.physical
    if (selectedSections.subscriptions) data.subscriptions = exportData.subscriptions
    if (selectedSections.contacts) data.contacts = exportData.contacts
    downloadFile(JSON.stringify(data, null, 2), 'deal-readiness-report.json', 'application/json')
    setIsLoading(false)
  }

  const handleExport = () => {
    if (exportFormat === 'pdf') generatePDF()
    else if (exportFormat === 'csv') generateCSV()
    else generateJSON()
  }

  const totalItems = exportData ? 
    (selectedSections.contracts ? exportData.contracts.length : 0) +
    (selectedSections.digital ? exportData.digital.length : 0) +
    (selectedSections.physical ? exportData.physical.length : 0) +
    (selectedSections.subscriptions ? exportData.subscriptions.length : 0) +
    (selectedSections.contacts ? exportData.contacts.length : 0) : 0

  return (
    <div className="max-w-2xl mx-auto">
      <div className="mb-8">
        <h1 className="text-2xl font-semibold text-white">Download Report</h1>
        <p className="mt-1 text-[#71717a]">Generate a Deal Readiness Report for due diligence</p>
      </div>

      <div className="bg-[#0f0f12] border border-[#1e1e23] rounded-xl p-6 mb-6">
        <div className="flex items-center gap-4">
          <div className="text-3xl">{completeness.readinessLevel === 'Deal-Ready' ? '✓' : '📋'}</div>
          <div>
            <h2 className="font-medium text-white">{completeness.readinessLevel}</h2>
            <p className="text-sm text-[#71717a]">{completeness.completedSections} of {completeness.totalSections} sections complete</p>
          </div>
        </div>
      </div>

      <div className="bg-[#0f0f12] border border-[#1e1e23] rounded-xl p-6 mb-6">
        <h2 className="text-lg font-medium text-white mb-4">Report Options</h2>

        <div className="mb-6">
          <label className="block text-sm font-medium text-[#a1a1aa] mb-3">Format</label>
          <div className="flex gap-3">
            {(['pdf', 'csv', 'json'] as const).map((format) => (
              <button key={format} onClick={() => setExportFormat(format)} className={`px-4 py-2 rounded-lg text-sm font-medium ${exportFormat === format ? 'bg-[#f59e0b] text-black' : 'bg-[#18181b] text-[#71717a] hover:bg-[#27272a]'}`}>
                {format.toUpperCase()}
              </button>
            ))}
          </div>
        </div>

        <div className="mb-6">
          <label className="block text-sm font-medium text-[#a1a1aa] mb-3">Include Sections</label>
          <div className="space-y-2">
            {[
              { key: 'contracts', label: 'Contracts & Legal', count: exportData?.contracts.length || 0 },
              { key: 'digital', label: 'Digital Infrastructure', count: exportData?.digital.length || 0 },
              { key: 'physical', label: 'Physical Assets', count: exportData?.physical.length || 0 },
              { key: 'subscriptions', label: 'Subscriptions', count: exportData?.subscriptions.length || 0 },
              { key: 'contacts', label: 'Key Relationships', count: exportData?.contacts.length || 0 },
            ].map((section) => (
              <label key={section.key} className="flex items-center gap-3 p-2 hover:bg-[#18181b] rounded-lg cursor-pointer">
                <input type="checkbox" checked={selectedSections[section.key as keyof typeof selectedSections]} onChange={(e) => setSelectedSections({ ...selectedSections, [section.key]: e.target.checked })} className="w-4 h-4 rounded" />
                <span className="flex-1 text-white">{section.label}</span>
                <span className="text-sm text-[#52525b]">{section.count} items</span>
              </label>
            ))}
          </div>
        </div>

        <div className="p-4 bg-[#18181b] rounded-lg mb-6">
          <p className="text-sm text-[#71717a]">Your report will include <span className="text-white font-medium">{totalItems} items</span>.</p>
        </div>

        <button onClick={handleExport} disabled={isLoading || totalItems === 0} className="w-full px-4 py-3 bg-[#f59e0b] text-black font-medium rounded-lg hover:bg-[#d97706] disabled:opacity-50">
          {isLoading ? 'Generating...' : `Download ${exportFormat.toUpperCase()} Report`}
        </button>
      </div>
    </div>
  )
}
